spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/openbill?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: openbill_dev
    password: billing!Q
    thymeleaf:
    cache: false   

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8888   
